### ISSUE TITLE
AboutScreen se ne otvara kao modal

### ISSUE THREAD

**Issue by mi5ha** [milosciganovic/ByteoutDemo#11]
Moras da namestis da se AboutScreen otvara kao modal, odozdo na gore se pojavljuje, a ne kao deo obicnog Stacka. Ima u notebooks kako se to radi.

U https://github.com/milosciganovic/ByteoutDemo/issues/4#issue-624766021 stoji koji navigator treba da bude modal navigator.

Dodaj i Close button u AboutScreen koji koristi goBack()

**Comment by milosciganovic** [comment]
Nasao sam u notebooks ovaj deo za modal na stack navigatoru 

mode="modal" 
medjutim to mi nije radilo, pa sam probao da shvatim sta je i skapirao ovaj deo koda                 ...TransitionPresets.SlideFromRightIOS, bio je preuzet sa primera pa ga nisam odmah video. 

Tada radi, medjutim kada obrsiem taj deo koda i kada obrisem mode = "modal" on i dalje otvara about kao modal, znaci sve je isto kao i kad stavim mode = "modal". Nisam siguran da li ja negde gresim

**Comment by milosciganovic** [comment]
Ubacio sam close button, radi super ali sam prebacio na Button iz paper biblioteke medjutim on mi vraca neki cudan error u type-script-u. Pretpostavljam da vec znas o cemu je rec. Inace button radi posao super tak oda verujem da je nesto vezano za tip

**Comment by mi5ha** [comment]
> Nasao sam u notebooks ovaj deo za modal na stack navigatoru
> 
> mode="modal"
> medjutim to mi nije radilo, pa sam probao da shvatim sta je i skapirao ovaj deo koda ...TransitionPresets.SlideFromRightIOS, bio je preuzet sa primera pa ga nisam odmah video.
> 
> Tada radi, medjutim kada obrsiem taj deo koda i kada obrisem mode = "modal" on i dalje otvara about kao modal, znaci sve je isto kao i kad stavim mode = "modal". Nisam siguran da li ja negde gresim

E znas sta je fora. Android po defaultu koristi modal animaciju za stack, iOS ne.

Zato sam i stavio `...TransitionPresets.SlideFromRightIOS,` da bi animacija na androidu bila ista kao na iosu.

Znaci u pravu si mode="modal" je default na Androidu pa se nista ne menja, al moras to da stavis bez obzira, zbog iosa.

**Comment by mi5ha** [comment]
nisi komitovao ovo za paper pa ne mogu da pogledam
