### ISSUE TITLE
Re-render bez potrebe?

### ISSUE THREAD

**Issue by mi5ha** [milosciganovic/ByteoutDemo#22]
https://github.com/milosciganovic/ByteoutDemo/blob/51a858a8e13998faa6afa4ff5609f5a73417369b/src/app/RootStackNav/AboutScreen.tsx#L24

Sta mislis da li ce se ovde dogoditi rerender Buttona svaki put kad se renderuje AboutScreen?

A ne bi trebalo jel da posto Button ima samo dva propertija koja se ne menjaju kad se AboutScreen rerenderuje.

**Comment by milosciganovic** [comment]
Nisam obratio paznju :D prebacicu Button u PURE :)

**Comment by mi5ha** [comment]
I ja neki put ovo radim mrzi me drugacije :-) al nakupe se renderi kad imas veliki app, pa se trudim da izbacim ovo skroz
