### ISSUE TITLE
Zar ne treba ovde ArticleScreen?

### ISSUE THREAD

**Issue by mi5ha** [milosciganovic/ByteoutDemo#23]
https://github.com/milosciganovic/ByteoutDemo/blob/51a858a8e13998faa6afa4ff5609f5a73417369b/src/app/RootStackNav/HomeDrawerNav/NewsTabNav/AllNewsStackNav/ArticleScreen.tsx#L18

**Comment by milosciganovic** [comment]
Verovatno sam nesto testirao pa zaboravio da izmenim -.-
