### ISSUE TITLE
Create navigation tree

### ISSUE THREAD

**Issue by mi5ha** [milosciganovic/ByteoutDemo#4]
### NAVIGATION TREE

- RootStackNav (modal)
    - HomeDrawerNav
        - NewsTabNav
            - AllNewsStackNav
                - NewsScreen
                - ArticleScreen
            - TopNewsScreen
        - SettingsScreen
    - AboutScreen

### TAB NAVIGATOR
- Add some random icons to tabs
- They should have proper color

**Comment by milosciganovic** [comment]
Nadam se da je to to. 

Trudio sam se da ne kopiram mnogo iz primera na one note nego da otkucam kako bih lakse razumeo tako da na neki mestima nisam ubacivao stvari koje mi nisu potrebne direktno za zadatak. 

Tipa: 
AboutScreen nema ni navigation props ni RouteProp jer ih ne koristim, ali tamo gde ih koristim sam ubacio. Ukoliko bude trebalo za kasnije ubacicu, ovako mi je delovalo cistije da ne kopiram bespotrebne stvari a i lakse sam razumeo. 

Ove ikonice nemaju outline pa sam samo promenio boju na active

**Comment by mi5ha** [comment]
Ma da, ono i jeste namenjeno kao dobra osnova da se ne krece od praznog papira, al onda tweakujes.

Ovaj package za RN ikone zapravo sadrzi preko 10 kolekcija ikona, FontAwesome imaju outline verziju, a i Ionic cini mi se a mozda i jos neki.

**Comment by milosciganovic** [comment]
Da to za ikonice sam zapravo video nego reko ajde nije tolko bitno pa sam na brzinu uradio resenje :)
