### ISSUE TITLE
All screen components get route and navigation

### ISSUE THREAD

**Issue by mi5ha** [milosciganovic/ByteoutDemo#6]
https://github.com/milosciganovic/ByteoutDemo/blob/023e375b323d34d69ed8d8093add351c33552b49/src/app/RootStackNav/AboutScreen.tsx#L4

Kad bolje razmislim, sve screen componente automatski dobijaju route i navigation property, cak i ako ga ti ne deklarises u screen componenti. Al onda si pogresno deklarisao tu komponentu, posto ta dva propertija postoje bez obzira da li si ih ti deklarisao ili ne.

Type dekleracija postoje samo na nivou TS-a, one nestaju kad se TS pretvori u JS, tako da krajnji JS nece imati nista vise codea (nit je to bitno na ovom nivou)

Tako da ipak ubuduce UVEK deklarisi route/navigation, bez obzira da li koristis ili ne. Posto oni uvek postoje ima logike da se to radi.

**Comment by milosciganovic** [comment]
Okej, moja logika se vise zasnivala na tome da na prvi pogled komponente screen komponente lakse skapiramo sta se tu desava. Tipa ako komponenta nema route i navigation property odmah mozemo da skapiramo da ne radi nista, ili ako ima samo jedan od ta dva mozemo da znamo otprilike sta radi ta komonenta, odnosno jednostavno da ne deklarisem ono sto ne koristim "no-unused vars". Mada je to diskutabilno kapiram da i sa deklaracijom moze da se snadje bez vecih problema.

**Comment by mi5ha** [comment]
Cenim da je to pitanje navike. Cela deklaracija je u startu, sama komponeta je i dalje praznjikava. Meni se ne svidja sto u suprotnom komponenta laze :-) Ako navigator vec injectuje te properije onda to treba da pise. Da ja mogu nekako da kazem navigatoru da ih ne injectuje kad ih ne koristim, onda bi bilo ok, ovako ti props su tu pa su tu.

**Comment by milosciganovic** [comment]
Jasno, ima logike.

**Comment by milosciganovic** [comment]
Dodao na TopNewsScreen
