### ISSUE TITLE
Phantom RootTabNav?

### ISSUE THREAD

**Issue by mi5ha** [milosciganovic/ByteoutDemo#7]
Nigde u opisu navigatora nije dat RootTabNav, zasto postoji taj folder?

Takodje, ideja je da postoji samo JEDAN navigator koji je Root, onaj koji je zaista root navigator stabla.

**Comment by milosciganovic** [comment]
Mislim da sam dok sam citao dokumentaciju bukvalno shvatio deo gde pise rootTabBar pa kasnije dok sam skapirao koja je logika zaboravio da izmenim taj folder. Po nekoj logici to bi trebao da bude folder **HomeDrawerNav** ako se ne varam?

**Comment by mi5ha** [comment]
da. Bukvalno onako kako je dato u opisu navigacionog stabla, struktura fileova i foldera nam sluzi da vidimo navigaciono stablo.

**Comment by milosciganovic** [comment]
Jasno, pusovacu to sa sledecom izmenom, sve isto samo beez nepotrebnog rootTabBar-a. Bih i ranije nego sam ga totalno zaboravio
